### ISSUE TITLE
KeyError: 'content' when trying to access preview.description

### ISSUE THREAD

**Issue by asmaier** [meyt/linkpreview#2]
Hello,

I really like your linkpreview package. It is very useful and easy to use. 
Unfortunately I have a problem when generating a preview for a specific website:

    from linkpreview import Link, LinkPreview, LinkGrabber
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36'}
    url = "http://queue.acm.org/detail.cfm?id=2891413"
    grabber = LinkGrabber()
    link = Link(url, grabber.get_content(url, headers=headers))
    preview = LinkPreview(link)
    print(preview.description)
    
When executing the code snippet above  I get the following error message

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.venv/lib/python3.9/site-packages/linkpreview/helpers.py", line 33, in __get__
    val = f(obj)
  File "~/.venv/lib/python3.9/site-packages/linkpreview/preview.py", line 181, in description
    return self._find_attribute("description")
  File "~/.venv/lib/python3.9/site-packages/linkpreview/preview.py", line 171, in _find_attribute
    value = getattr(obj, name)
  File "~/.venv/lib/python3.9/site-packages/linkpreview/preview.py", line 54, in description
    if meta and meta["content"]:
  File "~/.venv/lib/python3.9/site-packages/bs4/element.py", line 1406, in __getitem__
    return self.attrs[key]
KeyError: 'content'
```

Am I doing something wrong or is this a bug?

**Comment by meyt** [comment]
Hi @asmaier, 

I'm glad you like it and thanks for report.
The URL (http://queue.acm.org/detail.cfm?id=2891413) has an invalid meta attribute and uses `value` instead of `content` for description meta tag. now the error fixed, after [v0.1.12](https://pypi.org/project/linkpreview/0.1.12/) LinkPreview will ignore invalid meta and return `None`.
